### ISSUE TITLE
3D Modell Textur

### ISSUE THREAD

**Issue by RealHtler** [philippAuinger/htl-leonding-3D-tadeot#1]
Es wäre wirklich toll wenn das 3d Modell eine Textur bekommen würde. Versuche gerade eine CSGO Map aus der Schule zu machen und ohne Texturen sieht es nicht so gut aus. Lg RealHtler

**Comment by philipp323** [comment]
1. I bin nimma an da Schui
2. Wenn du ned als nächster Schüler in da Kronen-Zeitung stehn willst, weila sei Schui mid Waffen in Verbindung bringt, würdi da raten dei Vorhaben abzubrechen.
Schwammal
